# @Author: guiguan
# @Date:   2017-02-15T07:18:20+11:00
# @Last modified by:   guiguan
# @Last modified time: 2017-03-03T10:11:57+11:00

outlinks:
  - dbenvy
volumeMappings:
  - node: global
    name: npm-cache
    path: ~/.npm
