# @Author: guiguan
# @Date:   2017-01-09T15:15:34+11:00
# @Last modified by:   guiguan
# @Last modified time: 2017-06-16T16:49:20+10:00



pipeline:
  cienvy:
    image: southbanksoftware/cienvy:node-nm-mongo
    pull: true
    commands:
      - yarn install
      - yarn test
branches: master
