# @Author: guiguan
# @Date:   2017-01-09T15:15:34+11:00
# @Last modified by:   guiguan
# @Last modified time: 2017-06-16T16:49:20+10:00



pipeline:
  cienvy:
    image: southbanksoftware/cienvy:node-nm-mongo
    pull: true
    volumes:
      - /home/core/cienvy-client:/cienvy-client
      - cienvy-volumes:/volumes
    commands:
      - bash /cienvy-client/bin/cienvy.bash --url=http://172.16.0.1:9090 prepare core
branches: master
