# @Author: Guan Gui <guiguan>
# @Date:   2016-06-02T14:58:00+10:00
# @Email:  root@guiguan.net
# @Last modified by:   guiguan
# @Last modified time: 2017-12-15T13:31:33+11:00

extends: [airbnb, plugin:flowtype/recommended]
parser: babel-eslint
env:
  browser: true
  node: true
  jest: true
  es6: true
rules:
  no-continue: off
  no-labels: off
  arrow-body-style: off
  key-spacing: off
  object-property-newline: off
  no-cond-assign: [error, except-parens]
  no-nested-ternary: off
  no-shadow: off
  eqeqeq: off
  array-callback-return: off
  no-param-reassign: off
  space-before-function-paren: off
  global-require: off
  consistent-return: off
  quote-props: off
  linebreak-style: off
  no-underscore-dangle: off
  prefer-const: [error, {ignoreReadBeforeAssign: true}]
  max-len: off
  prefer-template: off
  object-curly-spacing: off
  comma-dangle: off
  object-curly-newline: [off, {
    ObjectExpression: { minProperties: 0, multiline: true },
    ObjectPattern: { minProperties: 0, multiline: true }
  }]
  jsx-a11y/label-has-for: off
  jsx-a11y/interactive-supports-focus: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/no-noninteractive-element-interactions: off
  function-paren-newline: off
  no-restricted-globals: off
  indent: off
  no-console: off
  no-alert: off
  no-multiple-empty-lines: [error, {max: 3}]
  func-names: off
  new-cap: [error, {capIsNew: false}]
  import/default: off
  import/no-duplicates: off
  import/named: off
  import/namespace: off
  import/no-named-as-default: error
  # this requires eslint-import-resolver-node@0.3.0 to be installed in order for import/resolver settings to work
  import/no-unresolved: [error, {ignore: ["^[~]", "^[#]"]}]
  import/prefer-default-export: off
  import/no-extraneous-dependencies: off
  import/extensions: off
  react/prefer-stateless-function: off
  react/jsx-space-before-closing: off
  react/jsx-first-prop-new-line: off
  react/jsx-closing-bracket-location: off
  react/no-multi-comp: off
  react/no-did-mount-set-state: off
  react/prop-types: off
  react/sort-comp: off
  react/no-unused-prop-types: off
  react/no-unused-state: off
  react/jsx-max-props-per-line: off
  react/prefer-es6-class: off
  react/require-default-props: off
  react/forbid-prop-types: off
  no-unused-vars: [error, {argsIgnorePattern: ^_}]
  no-restricted-syntax: off
  no-unused-expressions: off
  newline-per-chained-call: off
  class-methods-use-this: off
  no-multi-str: off
  no-useless-escape: off
  no-use-before-define: [error, {functions: false, classes: true}]
  no-mixed-operators: off
  no-return-assign: [error, except-parens]
  no-prototype-builtins: off
  prefer-destructuring: warn
  prefer-promise-reject-errors: warn
  no-control-regex: off
  flowtype/no-types-missing-file-annotation: off
  flowtype/generic-spacing: off
plugins: [react, import, flowtype]
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - src
globals:
  l: false
  globalString: false
  globalNumber: false
  IS_ELECTRON: false
  GetRandomPort: false
