// flow-typed signature: 94268c9ab66b218304352fb1ddd1eacf
// flow-typed version: <<STUB>>/codemirror-colorpicker_v^1.0.8/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codemirror-colorpicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codemirror-colorpicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codemirror-colorpicker/addon/colorpicker/colorpicker' {
  declare module.exports: any;
}

declare module 'codemirror-colorpicker/addon/colorpicker/colorview' {
  declare module.exports: any;
}

// Filename aliases
declare module 'codemirror-colorpicker/addon/colorpicker/colorpicker.js' {
  declare module.exports: $Exports<'codemirror-colorpicker/addon/colorpicker/colorpicker'>;
}
declare module 'codemirror-colorpicker/addon/colorpicker/colorview.js' {
  declare module.exports: $Exports<'codemirror-colorpicker/addon/colorpicker/colorview'>;
}
