// flow-typed signature: 9baeb7abc0435f160c8401fb85e879c9
// flow-typed version: <<STUB>>/codemirror-formatting_v^1.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codemirror-formatting'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codemirror-formatting' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codemirror-formatting/formatting' {
  declare module.exports: any;
}

// Filename aliases
declare module 'codemirror-formatting/formatting.js' {
  declare module.exports: $Exports<'codemirror-formatting/formatting'>;
}
