// flow-typed signature: 2add13c7ddd79debef9e201649d708ac
// flow-typed version: <<STUB>>/codemirror-highlight_v^1.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codemirror-highlight'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codemirror-highlight' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codemirror-highlight/lib/highlight' {
  declare module.exports: any;
}

declare module 'codemirror-highlight/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'codemirror-highlight/lib/highlight.js' {
  declare module.exports: $Exports<'codemirror-highlight/lib/highlight'>;
}
declare module 'codemirror-highlight/test/test.js' {
  declare module.exports: $Exports<'codemirror-highlight/test/test'>;
}
