// flow-typed signature: 9bf7401e03eaefa9c231eee8cc7b1a83
// flow-typed version: <<STUB>>/dumpenvy_v^1.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dumpenvy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dumpenvy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dumpenvy/lib/dumpenvy' {
  declare module.exports: any;
}

declare module 'dumpenvy/lib/index' {
  declare module.exports: any;
}

declare module 'dumpenvy/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dumpenvy/lib/dumpenvy.js' {
  declare module.exports: $Exports<'dumpenvy/lib/dumpenvy'>;
}
declare module 'dumpenvy/lib/index.js' {
  declare module.exports: $Exports<'dumpenvy/lib/index'>;
}
declare module 'dumpenvy/lib/utils.js' {
  declare module.exports: $Exports<'dumpenvy/lib/utils'>;
}
