// flow-typed signature: a88d20d3b14daeca5bc279c99cd4a371
// flow-typed version: <<STUB>>/eslint-import-resolver-node_v^0.3.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-import-resolver-node/index' {
  declare module.exports: $Exports<'eslint-import-resolver-node'>;
}
declare module 'eslint-import-resolver-node/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-node'>;
}
