// flow-typed signature: 36f78cf333106d888deff4f86565b497
// flow-typed version: <<STUB>>/feathers-primus_v^2.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feathers-primus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feathers-primus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feathers-primus/client' {
  declare module.exports: any;
}

declare module 'feathers-primus/lib/client' {
  declare module.exports: any;
}

declare module 'feathers-primus/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feathers-primus/client.js' {
  declare module.exports: $Exports<'feathers-primus/client'>;
}
declare module 'feathers-primus/lib/client.js' {
  declare module.exports: $Exports<'feathers-primus/lib/client'>;
}
declare module 'feathers-primus/lib/index.js' {
  declare module.exports: $Exports<'feathers-primus/lib/index'>;
}
