// flow-typed signature: f94573a676ae96cc2f46e4ad2b2e1f86
// flow-typed version: <<STUB>>/feathers-client_v^1.9.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feathers-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feathers-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feathers-client/dist/feathers' {
  declare module.exports: any;
}

declare module 'feathers-client/dist/feathers.min' {
  declare module.exports: any;
}

declare module 'feathers-client/Gruntfile' {
  declare module.exports: any;
}

declare module 'feathers-client/lib/client' {
  declare module.exports: any;
}

declare module 'feathers-client/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feathers-client/dist/feathers.js' {
  declare module.exports: $Exports<'feathers-client/dist/feathers'>;
}
declare module 'feathers-client/dist/feathers.min.js' {
  declare module.exports: $Exports<'feathers-client/dist/feathers.min'>;
}
declare module 'feathers-client/Gruntfile.js' {
  declare module.exports: $Exports<'feathers-client/Gruntfile'>;
}
declare module 'feathers-client/lib/client.js' {
  declare module.exports: $Exports<'feathers-client/lib/client'>;
}
declare module 'feathers-client/version.js' {
  declare module.exports: $Exports<'feathers-client/version'>;
}
