// flow-typed signature: a7d6f51efaea088ede76325b83adde6f
// flow-typed version: <<STUB>>/globalize-webpack-plugin_v^1.0.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'globalize-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'globalize-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'globalize-webpack-plugin/DevelopmentModePlugin' {
  declare module.exports: any;
}

declare module 'globalize-webpack-plugin/GlobalizeCompilerHelper' {
  declare module.exports: any;
}

declare module 'globalize-webpack-plugin/PatchedRawModule' {
  declare module.exports: any;
}

declare module 'globalize-webpack-plugin/ProductionModePlugin' {
  declare module.exports: any;
}

declare module 'globalize-webpack-plugin/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'globalize-webpack-plugin/DevelopmentModePlugin.js' {
  declare module.exports: $Exports<'globalize-webpack-plugin/DevelopmentModePlugin'>;
}
declare module 'globalize-webpack-plugin/GlobalizeCompilerHelper.js' {
  declare module.exports: $Exports<'globalize-webpack-plugin/GlobalizeCompilerHelper'>;
}
declare module 'globalize-webpack-plugin/index' {
  declare module.exports: $Exports<'globalize-webpack-plugin'>;
}
declare module 'globalize-webpack-plugin/index.js' {
  declare module.exports: $Exports<'globalize-webpack-plugin'>;
}
declare module 'globalize-webpack-plugin/PatchedRawModule.js' {
  declare module.exports: $Exports<'globalize-webpack-plugin/PatchedRawModule'>;
}
declare module 'globalize-webpack-plugin/ProductionModePlugin.js' {
  declare module.exports: $Exports<'globalize-webpack-plugin/ProductionModePlugin'>;
}
declare module 'globalize-webpack-plugin/util.js' {
  declare module.exports: $Exports<'globalize-webpack-plugin/util'>;
}
