// flow-typed signature: c16bfebc3ff9cb13c0755b75f1eefd45
// flow-typed version: <<STUB>>/globalize_v^1.2.3/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'globalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'globalize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'globalize/dist/globalize-runtime' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize-runtime/currency' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize-runtime/date' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize-runtime/message' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize-runtime/number' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize-runtime/plural' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize-runtime/relative-time' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize-runtime/unit' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize/currency' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize/date' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize/message' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize/number' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize/plural' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize/relative-time' {
  declare module.exports: any;
}

declare module 'globalize/dist/globalize/unit' {
  declare module.exports: any;
}

declare module 'globalize/dist/node-main' {
  declare module.exports: any;
}

declare module 'globalize/examples/amd-bower/main' {
  declare module.exports: any;
}

declare module 'globalize/examples/app-npm-webpack-2/app/index' {
  declare module.exports: any;
}

declare module 'globalize/examples/app-npm-webpack-2/webpack-config' {
  declare module.exports: any;
}

declare module 'globalize/examples/app-npm-webpack/app/index' {
  declare module.exports: any;
}

declare module 'globalize/examples/app-npm-webpack/webpack-config' {
  declare module.exports: any;
}

declare module 'globalize/examples/globalize-compiler/app' {
  declare module.exports: any;
}

declare module 'globalize/examples/node-npm/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'globalize/dist/globalize-runtime.js' {
  declare module.exports: $Exports<'globalize/dist/globalize-runtime'>;
}
declare module 'globalize/dist/globalize-runtime/currency.js' {
  declare module.exports: $Exports<'globalize/dist/globalize-runtime/currency'>;
}
declare module 'globalize/dist/globalize-runtime/date.js' {
  declare module.exports: $Exports<'globalize/dist/globalize-runtime/date'>;
}
declare module 'globalize/dist/globalize-runtime/message.js' {
  declare module.exports: $Exports<'globalize/dist/globalize-runtime/message'>;
}
declare module 'globalize/dist/globalize-runtime/number.js' {
  declare module.exports: $Exports<'globalize/dist/globalize-runtime/number'>;
}
declare module 'globalize/dist/globalize-runtime/plural.js' {
  declare module.exports: $Exports<'globalize/dist/globalize-runtime/plural'>;
}
declare module 'globalize/dist/globalize-runtime/relative-time.js' {
  declare module.exports: $Exports<'globalize/dist/globalize-runtime/relative-time'>;
}
declare module 'globalize/dist/globalize-runtime/unit.js' {
  declare module.exports: $Exports<'globalize/dist/globalize-runtime/unit'>;
}
declare module 'globalize/dist/globalize.js' {
  declare module.exports: $Exports<'globalize/dist/globalize'>;
}
declare module 'globalize/dist/globalize/currency.js' {
  declare module.exports: $Exports<'globalize/dist/globalize/currency'>;
}
declare module 'globalize/dist/globalize/date.js' {
  declare module.exports: $Exports<'globalize/dist/globalize/date'>;
}
declare module 'globalize/dist/globalize/message.js' {
  declare module.exports: $Exports<'globalize/dist/globalize/message'>;
}
declare module 'globalize/dist/globalize/number.js' {
  declare module.exports: $Exports<'globalize/dist/globalize/number'>;
}
declare module 'globalize/dist/globalize/plural.js' {
  declare module.exports: $Exports<'globalize/dist/globalize/plural'>;
}
declare module 'globalize/dist/globalize/relative-time.js' {
  declare module.exports: $Exports<'globalize/dist/globalize/relative-time'>;
}
declare module 'globalize/dist/globalize/unit.js' {
  declare module.exports: $Exports<'globalize/dist/globalize/unit'>;
}
declare module 'globalize/dist/node-main.js' {
  declare module.exports: $Exports<'globalize/dist/node-main'>;
}
declare module 'globalize/examples/amd-bower/main.js' {
  declare module.exports: $Exports<'globalize/examples/amd-bower/main'>;
}
declare module 'globalize/examples/app-npm-webpack-2/app/index.js' {
  declare module.exports: $Exports<'globalize/examples/app-npm-webpack-2/app/index'>;
}
declare module 'globalize/examples/app-npm-webpack-2/webpack-config.js' {
  declare module.exports: $Exports<'globalize/examples/app-npm-webpack-2/webpack-config'>;
}
declare module 'globalize/examples/app-npm-webpack/app/index.js' {
  declare module.exports: $Exports<'globalize/examples/app-npm-webpack/app/index'>;
}
declare module 'globalize/examples/app-npm-webpack/webpack-config.js' {
  declare module.exports: $Exports<'globalize/examples/app-npm-webpack/webpack-config'>;
}
declare module 'globalize/examples/globalize-compiler/app.js' {
  declare module.exports: $Exports<'globalize/examples/globalize-compiler/app'>;
}
declare module 'globalize/examples/node-npm/main.js' {
  declare module.exports: $Exports<'globalize/examples/node-npm/main'>;
}
