// flow-typed signature: 8d2ce51b476ecb48e083677b4cad56bd
// flow-typed version: <<STUB>>/handlebars-loader_v^1.5.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'handlebars-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'handlebars-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'handlebars-loader/lib/fastreplace' {
  declare module.exports: any;
}

declare module 'handlebars-loader/lib/findNestedRequires' {
  declare module.exports: any;
}

// Filename aliases
declare module 'handlebars-loader/index' {
  declare module.exports: $Exports<'handlebars-loader'>;
}
declare module 'handlebars-loader/index.js' {
  declare module.exports: $Exports<'handlebars-loader'>;
}
declare module 'handlebars-loader/lib/fastreplace.js' {
  declare module.exports: $Exports<'handlebars-loader/lib/fastreplace'>;
}
declare module 'handlebars-loader/lib/findNestedRequires.js' {
  declare module.exports: $Exports<'handlebars-loader/lib/findNestedRequires'>;
}
