// flow-typed signature: ee34a12437bb651a4bf092b5f2d183ca
// flow-typed version: <<STUB>>/lazy-route_v^1.0.7/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lazy-route'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lazy-route' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lazy-route/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lazy-route/lib/index.js' {
  declare module.exports: $Exports<'lazy-route/lib/index'>;
}
