// flow-typed signature: e507afa32d23c8a53100a13b690cc1e3
// flow-typed version: <<STUB>>/little-loader_v^0.2.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'little-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'little-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'little-loader/dist/little-loader.min' {
  declare module.exports: any;
}

declare module 'little-loader/lib/little-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'little-loader/dist/little-loader.min.js' {
  declare module.exports: $Exports<'little-loader/dist/little-loader.min'>;
}
declare module 'little-loader/lib/little-loader.js' {
  declare module.exports: $Exports<'little-loader/lib/little-loader'>;
}
