// flow-typed signature: 2749e794ca43ff50221305ff681e05c3
// flow-typed version: <<STUB>>/mongodb-uri_v^0.9.7/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongodb-uri'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongodb-uri' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongodb-uri/mongodb-uri' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongodb-uri/mongodb-uri.js' {
  declare module.exports: $Exports<'mongodb-uri/mongodb-uri'>;
}
