// flow-typed signature: 1ccfdad44bd845f5a66247ae7b45646d
// flow-typed version: <<STUB>>/mongo-shell-translator_v0.0.1-alpha.12/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongo-shell-translator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongo-shell-translator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongo-shell-translator/dist/argument-creator' {
  declare module.exports: any;
}

declare module 'mongo-shell-translator/dist/code-generator' {
  declare module.exports: any;
}

declare module 'mongo-shell-translator/dist/common-translator' {
  declare module.exports: any;
}

declare module 'mongo-shell-translator/dist/delete-translator' {
  declare module.exports: any;
}

declare module 'mongo-shell-translator/dist/find-one-translator' {
  declare module.exports: any;
}

declare module 'mongo-shell-translator/dist/find-translator' {
  declare module.exports: any;
}

declare module 'mongo-shell-translator/dist/index' {
  declare module.exports: any;
}

declare module 'mongo-shell-translator/dist/insert-translator' {
  declare module.exports: any;
}

declare module 'mongo-shell-translator/dist/mongo-shell-translator' {
  declare module.exports: any;
}

declare module 'mongo-shell-translator/dist/options' {
  declare module.exports: any;
}

declare module 'mongo-shell-translator/dist/update-translator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongo-shell-translator/dist/argument-creator.js' {
  declare module.exports: $Exports<'mongo-shell-translator/dist/argument-creator'>;
}
declare module 'mongo-shell-translator/dist/code-generator.js' {
  declare module.exports: $Exports<'mongo-shell-translator/dist/code-generator'>;
}
declare module 'mongo-shell-translator/dist/common-translator.js' {
  declare module.exports: $Exports<'mongo-shell-translator/dist/common-translator'>;
}
declare module 'mongo-shell-translator/dist/delete-translator.js' {
  declare module.exports: $Exports<'mongo-shell-translator/dist/delete-translator'>;
}
declare module 'mongo-shell-translator/dist/find-one-translator.js' {
  declare module.exports: $Exports<'mongo-shell-translator/dist/find-one-translator'>;
}
declare module 'mongo-shell-translator/dist/find-translator.js' {
  declare module.exports: $Exports<'mongo-shell-translator/dist/find-translator'>;
}
declare module 'mongo-shell-translator/dist/index.js' {
  declare module.exports: $Exports<'mongo-shell-translator/dist/index'>;
}
declare module 'mongo-shell-translator/dist/insert-translator.js' {
  declare module.exports: $Exports<'mongo-shell-translator/dist/insert-translator'>;
}
declare module 'mongo-shell-translator/dist/mongo-shell-translator.js' {
  declare module.exports: $Exports<'mongo-shell-translator/dist/mongo-shell-translator'>;
}
declare module 'mongo-shell-translator/dist/options.js' {
  declare module.exports: $Exports<'mongo-shell-translator/dist/options'>;
}
declare module 'mongo-shell-translator/dist/update-translator.js' {
  declare module.exports: $Exports<'mongo-shell-translator/dist/update-translator'>;
}
