// flow-typed signature: bf4d39b87a469707036c0b194f83b354
// flow-typed version: <<STUB>>/package_v^1.0.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'package'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'package' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'package/examples/custom_path' {
  declare module.exports: any;
}

declare module 'package/examples/module' {
  declare module.exports: any;
}

declare module 'package/lib/package' {
  declare module.exports: any;
}

declare module 'package/test/index.test' {
  declare module.exports: any;
}

declare module 'package/test/nested/two/nested.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'package/examples/custom_path.js' {
  declare module.exports: $Exports<'package/examples/custom_path'>;
}
declare module 'package/examples/module.js' {
  declare module.exports: $Exports<'package/examples/module'>;
}
declare module 'package/lib/package.js' {
  declare module.exports: $Exports<'package/lib/package'>;
}
declare module 'package/test/index.test.js' {
  declare module.exports: $Exports<'package/test/index.test'>;
}
declare module 'package/test/nested/two/nested.test.js' {
  declare module.exports: $Exports<'package/test/nested/two/nested.test'>;
}
