// flow-typed signature: 863af377f7ce499162bb6864983d37e8
// flow-typed version: <<STUB>>/prettier-standalone_v^1.3.1-0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-standalone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-standalone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-standalone/bundle' {
  declare module.exports: any;
}

declare module 'prettier-standalone/main' {
  declare module.exports: any;
}

declare module 'prettier-standalone/remove-use-strict' {
  declare module.exports: any;
}

declare module 'prettier-standalone/test' {
  declare module.exports: any;
}

declare module 'prettier-standalone/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-standalone/bundle.js' {
  declare module.exports: $Exports<'prettier-standalone/bundle'>;
}
declare module 'prettier-standalone/main.js' {
  declare module.exports: $Exports<'prettier-standalone/main'>;
}
declare module 'prettier-standalone/remove-use-strict.js' {
  declare module.exports: $Exports<'prettier-standalone/remove-use-strict'>;
}
declare module 'prettier-standalone/test.js' {
  declare module.exports: $Exports<'prettier-standalone/test'>;
}
declare module 'prettier-standalone/webpack.config.js' {
  declare module.exports: $Exports<'prettier-standalone/webpack.config'>;
}
