// flow-typed signature: a638ab3804b6430de48af0db0a1e5a37
// flow-typed version: <<STUB>>/react-json-viewer_v^1.6.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-json-viewer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-json-viewer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-json-viewer/dist/Example' {
  declare module.exports: any;
}

declare module 'react-json-viewer/dist/ReactJSONViewer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-json-viewer/dist/Example.js' {
  declare module.exports: $Exports<'react-json-viewer/dist/Example'>;
}
declare module 'react-json-viewer/dist/ReactJSONViewer.js' {
  declare module.exports: $Exports<'react-json-viewer/dist/ReactJSONViewer'>;
}
