// flow-typed signature: 37f5f51eaa82e759f8b9d1699a96269b
// flow-typed version: <<STUB>>/react-shortcut_v^1.0.6/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-shortcut'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-shortcut' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-shortcut/src/Component' {
  declare module.exports: any;
}

declare module 'react-shortcut/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-shortcut/src/Component.js' {
  declare module.exports: $Exports<'react-shortcut/src/Component'>;
}
declare module 'react-shortcut/src/index.js' {
  declare module.exports: $Exports<'react-shortcut/src/index'>;
}
