// flow-typed signature: 3463d76e0871dbd15e0c4329af81c5ce
// flow-typed version: <<STUB>>/react-codemirror_vgithub:SouthbankSoftware/react-codemirror/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-codemirror'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-codemirror' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-codemirror/dist/react-codemirror' {
  declare module.exports: any;
}

declare module 'react-codemirror/dist/react-codemirror.min' {
  declare module.exports: any;
}

declare module 'react-codemirror/example/src/example' {
  declare module.exports: any;
}

declare module 'react-codemirror/gulpfile' {
  declare module.exports: any;
}

declare module 'react-codemirror/lib/Codemirror' {
  declare module.exports: any;
}

declare module 'react-codemirror/src/Codemirror' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-codemirror/dist/react-codemirror.js' {
  declare module.exports: $Exports<'react-codemirror/dist/react-codemirror'>;
}
declare module 'react-codemirror/dist/react-codemirror.min.js' {
  declare module.exports: $Exports<'react-codemirror/dist/react-codemirror.min'>;
}
declare module 'react-codemirror/example/src/example.js' {
  declare module.exports: $Exports<'react-codemirror/example/src/example'>;
}
declare module 'react-codemirror/gulpfile.js' {
  declare module.exports: $Exports<'react-codemirror/gulpfile'>;
}
declare module 'react-codemirror/lib/Codemirror.js' {
  declare module.exports: $Exports<'react-codemirror/lib/Codemirror'>;
}
declare module 'react-codemirror/src/Codemirror.js' {
  declare module.exports: $Exports<'react-codemirror/src/Codemirror'>;
}
