// flow-typed signature: b657f697727deabddb997733a2f057d1
// flow-typed version: <<STUB>>/react-svg-loader_v^1.1.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-svg-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-svg-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-svg-loader/lib/camelize' {
  declare module.exports: any;
}

declare module 'react-svg-loader/lib/cli' {
  declare module.exports: any;
}

declare module 'react-svg-loader/lib/css-to-obj' {
  declare module.exports: any;
}

declare module 'react-svg-loader/lib/loader' {
  declare module.exports: any;
}

declare module 'react-svg-loader/lib/plugin' {
  declare module.exports: any;
}

declare module 'react-svg-loader/lib/svgo' {
  declare module.exports: any;
}

declare module 'react-svg-loader/src/camelize' {
  declare module.exports: any;
}

declare module 'react-svg-loader/src/cli' {
  declare module.exports: any;
}

declare module 'react-svg-loader/src/css-to-obj' {
  declare module.exports: any;
}

declare module 'react-svg-loader/src/loader' {
  declare module.exports: any;
}

declare module 'react-svg-loader/src/plugin' {
  declare module.exports: any;
}

declare module 'react-svg-loader/src/svgo' {
  declare module.exports: any;
}

declare module 'react-svg-loader/test/cli' {
  declare module.exports: any;
}

declare module 'react-svg-loader/test/css-to-obj' {
  declare module.exports: any;
}

declare module 'react-svg-loader/test/index' {
  declare module.exports: any;
}

declare module 'react-svg-loader/test/loader' {
  declare module.exports: any;
}

declare module 'react-svg-loader/test/resources/config' {
  declare module.exports: any;
}

declare module 'react-svg-loader/test/svgo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-svg-loader/lib/camelize.js' {
  declare module.exports: $Exports<'react-svg-loader/lib/camelize'>;
}
declare module 'react-svg-loader/lib/cli.js' {
  declare module.exports: $Exports<'react-svg-loader/lib/cli'>;
}
declare module 'react-svg-loader/lib/css-to-obj.js' {
  declare module.exports: $Exports<'react-svg-loader/lib/css-to-obj'>;
}
declare module 'react-svg-loader/lib/loader.js' {
  declare module.exports: $Exports<'react-svg-loader/lib/loader'>;
}
declare module 'react-svg-loader/lib/plugin.js' {
  declare module.exports: $Exports<'react-svg-loader/lib/plugin'>;
}
declare module 'react-svg-loader/lib/svgo.js' {
  declare module.exports: $Exports<'react-svg-loader/lib/svgo'>;
}
declare module 'react-svg-loader/src/camelize.js' {
  declare module.exports: $Exports<'react-svg-loader/src/camelize'>;
}
declare module 'react-svg-loader/src/cli.js' {
  declare module.exports: $Exports<'react-svg-loader/src/cli'>;
}
declare module 'react-svg-loader/src/css-to-obj.js' {
  declare module.exports: $Exports<'react-svg-loader/src/css-to-obj'>;
}
declare module 'react-svg-loader/src/loader.js' {
  declare module.exports: $Exports<'react-svg-loader/src/loader'>;
}
declare module 'react-svg-loader/src/plugin.js' {
  declare module.exports: $Exports<'react-svg-loader/src/plugin'>;
}
declare module 'react-svg-loader/src/svgo.js' {
  declare module.exports: $Exports<'react-svg-loader/src/svgo'>;
}
declare module 'react-svg-loader/test/cli.js' {
  declare module.exports: $Exports<'react-svg-loader/test/cli'>;
}
declare module 'react-svg-loader/test/css-to-obj.js' {
  declare module.exports: $Exports<'react-svg-loader/test/css-to-obj'>;
}
declare module 'react-svg-loader/test/index.js' {
  declare module.exports: $Exports<'react-svg-loader/test/index'>;
}
declare module 'react-svg-loader/test/loader.js' {
  declare module.exports: $Exports<'react-svg-loader/test/loader'>;
}
declare module 'react-svg-loader/test/resources/config.js' {
  declare module.exports: $Exports<'react-svg-loader/test/resources/config'>;
}
declare module 'react-svg-loader/test/svgo.js' {
  declare module.exports: $Exports<'react-svg-loader/test/svgo'>;
}
