// flow-typed signature: 6bcad4bd513fc35965d312bfaeff0a6c
// flow-typed version: <<STUB>>/shebang-loader_v0.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shebang-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shebang-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'shebang-loader/index' {
  declare module.exports: $Exports<'shebang-loader'>;
}
declare module 'shebang-loader/index.js' {
  declare module.exports: $Exports<'shebang-loader'>;
}
