// flow-typed signature: 991908b66a9d7bdba7dbe9eea4d06766
// flow-typed version: <<STUB>>/validatorjs_v^3.11.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'validatorjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'validatorjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'validatorjs/dist/lang/de' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/el' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/es' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/fa' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/fr' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/it' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/ja' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/nb_NO' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/pl' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/pt' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/ru' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/tr' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/vi' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/zh_TW' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/zh' {
  declare module.exports: any;
}

declare module 'validatorjs/Gruntfile' {
  declare module.exports: any;
}

declare module 'validatorjs/karma.conf' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/accepted-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/after_or_equal-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/after-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/alpha_dash-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/alpha_num-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/alpha-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/alternative-initialization' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/array' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/async-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/attribute-formatter' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/attribute-names' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/before_or_equal-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/before-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/between-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/boolean-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/confirmed-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/custom-messages' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/date-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/different-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/digits-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/email-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/error-count' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/error-messages' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/flatten-object' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/in-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/integer-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/lang' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/max-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/min-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/nested-rules' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/not_in-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/numeric-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/passes' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/present-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/regex-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/register' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/require-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/required_if' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/required_unless' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/required_with_all' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/required_with' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/required_without_all' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/required_without' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/same-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/size-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/sometimes-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/stop-on-error' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/string-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/url-rule' {
  declare module.exports: any;
}

declare module 'validatorjs/spec/validator' {
  declare module.exports: any;
}

declare module 'validatorjs/src/async' {
  declare module.exports: any;
}

declare module 'validatorjs/src/attributes' {
  declare module.exports: any;
}

declare module 'validatorjs/src/errors' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/de' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/el' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/en' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/es' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/fa' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/fr' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/it' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/ja' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/nb_NO' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/pl' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/pt' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/ru' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/tr' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/vi' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/zh_TW' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/zh' {
  declare module.exports: any;
}

declare module 'validatorjs/src/messages' {
  declare module.exports: any;
}

declare module 'validatorjs/src/rules' {
  declare module.exports: any;
}

declare module 'validatorjs/src/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'validatorjs/dist/lang/de.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/de'>;
}
declare module 'validatorjs/dist/lang/el.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/el'>;
}
declare module 'validatorjs/dist/lang/es.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/es'>;
}
declare module 'validatorjs/dist/lang/fa.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/fa'>;
}
declare module 'validatorjs/dist/lang/fr.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/fr'>;
}
declare module 'validatorjs/dist/lang/it.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/it'>;
}
declare module 'validatorjs/dist/lang/ja.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/ja'>;
}
declare module 'validatorjs/dist/lang/nb_NO.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/nb_NO'>;
}
declare module 'validatorjs/dist/lang/pl.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/pl'>;
}
declare module 'validatorjs/dist/lang/pt.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/pt'>;
}
declare module 'validatorjs/dist/lang/ru.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/ru'>;
}
declare module 'validatorjs/dist/lang/tr.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/tr'>;
}
declare module 'validatorjs/dist/lang/vi.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/vi'>;
}
declare module 'validatorjs/dist/lang/zh_TW.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/zh_TW'>;
}
declare module 'validatorjs/dist/lang/zh.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/zh'>;
}
declare module 'validatorjs/Gruntfile.js' {
  declare module.exports: $Exports<'validatorjs/Gruntfile'>;
}
declare module 'validatorjs/karma.conf.js' {
  declare module.exports: $Exports<'validatorjs/karma.conf'>;
}
declare module 'validatorjs/spec/accepted-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/accepted-rule'>;
}
declare module 'validatorjs/spec/after_or_equal-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/after_or_equal-rule'>;
}
declare module 'validatorjs/spec/after-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/after-rule'>;
}
declare module 'validatorjs/spec/alpha_dash-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/alpha_dash-rule'>;
}
declare module 'validatorjs/spec/alpha_num-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/alpha_num-rule'>;
}
declare module 'validatorjs/spec/alpha-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/alpha-rule'>;
}
declare module 'validatorjs/spec/alternative-initialization.js' {
  declare module.exports: $Exports<'validatorjs/spec/alternative-initialization'>;
}
declare module 'validatorjs/spec/array.js' {
  declare module.exports: $Exports<'validatorjs/spec/array'>;
}
declare module 'validatorjs/spec/async-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/async-rule'>;
}
declare module 'validatorjs/spec/attribute-formatter.js' {
  declare module.exports: $Exports<'validatorjs/spec/attribute-formatter'>;
}
declare module 'validatorjs/spec/attribute-names.js' {
  declare module.exports: $Exports<'validatorjs/spec/attribute-names'>;
}
declare module 'validatorjs/spec/before_or_equal-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/before_or_equal-rule'>;
}
declare module 'validatorjs/spec/before-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/before-rule'>;
}
declare module 'validatorjs/spec/between-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/between-rule'>;
}
declare module 'validatorjs/spec/boolean-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/boolean-rule'>;
}
declare module 'validatorjs/spec/confirmed-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/confirmed-rule'>;
}
declare module 'validatorjs/spec/custom-messages.js' {
  declare module.exports: $Exports<'validatorjs/spec/custom-messages'>;
}
declare module 'validatorjs/spec/date-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/date-rule'>;
}
declare module 'validatorjs/spec/different-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/different-rule'>;
}
declare module 'validatorjs/spec/digits-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/digits-rule'>;
}
declare module 'validatorjs/spec/email-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/email-rule'>;
}
declare module 'validatorjs/spec/error-count.js' {
  declare module.exports: $Exports<'validatorjs/spec/error-count'>;
}
declare module 'validatorjs/spec/error-messages.js' {
  declare module.exports: $Exports<'validatorjs/spec/error-messages'>;
}
declare module 'validatorjs/spec/flatten-object.js' {
  declare module.exports: $Exports<'validatorjs/spec/flatten-object'>;
}
declare module 'validatorjs/spec/in-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/in-rule'>;
}
declare module 'validatorjs/spec/integer-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/integer-rule'>;
}
declare module 'validatorjs/spec/lang.js' {
  declare module.exports: $Exports<'validatorjs/spec/lang'>;
}
declare module 'validatorjs/spec/max-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/max-rule'>;
}
declare module 'validatorjs/spec/min-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/min-rule'>;
}
declare module 'validatorjs/spec/nested-rules.js' {
  declare module.exports: $Exports<'validatorjs/spec/nested-rules'>;
}
declare module 'validatorjs/spec/not_in-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/not_in-rule'>;
}
declare module 'validatorjs/spec/numeric-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/numeric-rule'>;
}
declare module 'validatorjs/spec/passes.js' {
  declare module.exports: $Exports<'validatorjs/spec/passes'>;
}
declare module 'validatorjs/spec/present-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/present-rule'>;
}
declare module 'validatorjs/spec/regex-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/regex-rule'>;
}
declare module 'validatorjs/spec/register.js' {
  declare module.exports: $Exports<'validatorjs/spec/register'>;
}
declare module 'validatorjs/spec/require-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/require-rule'>;
}
declare module 'validatorjs/spec/required_if.js' {
  declare module.exports: $Exports<'validatorjs/spec/required_if'>;
}
declare module 'validatorjs/spec/required_unless.js' {
  declare module.exports: $Exports<'validatorjs/spec/required_unless'>;
}
declare module 'validatorjs/spec/required_with_all.js' {
  declare module.exports: $Exports<'validatorjs/spec/required_with_all'>;
}
declare module 'validatorjs/spec/required_with.js' {
  declare module.exports: $Exports<'validatorjs/spec/required_with'>;
}
declare module 'validatorjs/spec/required_without_all.js' {
  declare module.exports: $Exports<'validatorjs/spec/required_without_all'>;
}
declare module 'validatorjs/spec/required_without.js' {
  declare module.exports: $Exports<'validatorjs/spec/required_without'>;
}
declare module 'validatorjs/spec/same-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/same-rule'>;
}
declare module 'validatorjs/spec/size-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/size-rule'>;
}
declare module 'validatorjs/spec/sometimes-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/sometimes-rule'>;
}
declare module 'validatorjs/spec/stop-on-error.js' {
  declare module.exports: $Exports<'validatorjs/spec/stop-on-error'>;
}
declare module 'validatorjs/spec/string-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/string-rule'>;
}
declare module 'validatorjs/spec/url-rule.js' {
  declare module.exports: $Exports<'validatorjs/spec/url-rule'>;
}
declare module 'validatorjs/spec/validator.js' {
  declare module.exports: $Exports<'validatorjs/spec/validator'>;
}
declare module 'validatorjs/src/async.js' {
  declare module.exports: $Exports<'validatorjs/src/async'>;
}
declare module 'validatorjs/src/attributes.js' {
  declare module.exports: $Exports<'validatorjs/src/attributes'>;
}
declare module 'validatorjs/src/errors.js' {
  declare module.exports: $Exports<'validatorjs/src/errors'>;
}
declare module 'validatorjs/src/lang.js' {
  declare module.exports: $Exports<'validatorjs/src/lang'>;
}
declare module 'validatorjs/src/lang/de.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/de'>;
}
declare module 'validatorjs/src/lang/el.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/el'>;
}
declare module 'validatorjs/src/lang/en.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/en'>;
}
declare module 'validatorjs/src/lang/es.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/es'>;
}
declare module 'validatorjs/src/lang/fa.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/fa'>;
}
declare module 'validatorjs/src/lang/fr.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/fr'>;
}
declare module 'validatorjs/src/lang/it.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/it'>;
}
declare module 'validatorjs/src/lang/ja.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/ja'>;
}
declare module 'validatorjs/src/lang/nb_NO.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/nb_NO'>;
}
declare module 'validatorjs/src/lang/pl.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/pl'>;
}
declare module 'validatorjs/src/lang/pt.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/pt'>;
}
declare module 'validatorjs/src/lang/ru.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/ru'>;
}
declare module 'validatorjs/src/lang/tr.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/tr'>;
}
declare module 'validatorjs/src/lang/vi.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/vi'>;
}
declare module 'validatorjs/src/lang/zh_TW.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/zh_TW'>;
}
declare module 'validatorjs/src/lang/zh.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/zh'>;
}
declare module 'validatorjs/src/messages.js' {
  declare module.exports: $Exports<'validatorjs/src/messages'>;
}
declare module 'validatorjs/src/rules.js' {
  declare module.exports: $Exports<'validatorjs/src/rules'>;
}
declare module 'validatorjs/src/validator.js' {
  declare module.exports: $Exports<'validatorjs/src/validator'>;
}
