// flow-typed signature: a65feefcf23d71fa02459219b7d74dad
// flow-typed version: <<STUB>>/xterm_vx.x.x/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xterm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xterm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xterm/demo/app' {
  declare module.exports: any;
}

declare module 'xterm/demo/main' {
  declare module.exports: any;
}

declare module 'xterm/gulpfile' {
  declare module.exports: any;
}

declare module 'xterm/src/addons/attach/attach' {
  declare module.exports: any;
}

declare module 'xterm/src/addons/fit/fit' {
  declare module.exports: any;
}

declare module 'xterm/src/addons/fullscreen/fullscreen' {
  declare module.exports: any;
}

declare module 'xterm/src/addons/terminado/terminado' {
  declare module.exports: any;
}

declare module 'xterm/src/addons/zmodem/demo/app' {
  declare module.exports: any;
}

declare module 'xterm/src/addons/zmodem/demo/main' {
  declare module.exports: any;
}

declare module 'xterm/src/addons/zmodem/zmodem' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xterm/demo/app.js' {
  declare module.exports: $Exports<'xterm/demo/app'>;
}
declare module 'xterm/demo/main.js' {
  declare module.exports: $Exports<'xterm/demo/main'>;
}
declare module 'xterm/gulpfile.js' {
  declare module.exports: $Exports<'xterm/gulpfile'>;
}
declare module 'xterm/src/addons/attach/attach.js' {
  declare module.exports: $Exports<'xterm/src/addons/attach/attach'>;
}
declare module 'xterm/src/addons/fit/fit.js' {
  declare module.exports: $Exports<'xterm/src/addons/fit/fit'>;
}
declare module 'xterm/src/addons/fullscreen/fullscreen.js' {
  declare module.exports: $Exports<'xterm/src/addons/fullscreen/fullscreen'>;
}
declare module 'xterm/src/addons/terminado/terminado.js' {
  declare module.exports: $Exports<'xterm/src/addons/terminado/terminado'>;
}
declare module 'xterm/src/addons/zmodem/demo/app.js' {
  declare module.exports: $Exports<'xterm/src/addons/zmodem/demo/app'>;
}
declare module 'xterm/src/addons/zmodem/demo/main.js' {
  declare module.exports: $Exports<'xterm/src/addons/zmodem/demo/main'>;
}
declare module 'xterm/src/addons/zmodem/zmodem.js' {
  declare module.exports: $Exports<'xterm/src/addons/zmodem/zmodem'>;
}
