// flow-typed signature: 4fbdf82dfb7d962c7f959b0f845aea31
// flow-typed version: <<STUB>>/@blueprintjs/table_v^1.14.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blueprintjs/table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blueprintjs/table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blueprintjs/table/dist/cell/cell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/cell/editableCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/cell/formats/jsonFormat' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/cell/formats/truncatedFormat' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/column' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/common/batcher' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/common/cell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/common/classes' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/common/clipboard' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/common/contextMenuTargetWrapper' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/common/errors' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/common/grid' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/common/index' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/common/loadableContent' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/common/rect' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/common/requestIdleCallback' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/common/roundSize' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/common/utils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/headers/columnHeader' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/headers/columnHeaderCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/headers/editableName' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/headers/header' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/headers/headerCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/headers/rowHeader' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/headers/rowHeaderCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/index' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/interactions/dragEvents' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/interactions/draggable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/interactions/menus/copyCellsMenuItem' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/interactions/menus/index' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/interactions/menus/menuContext' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/interactions/reorderable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/interactions/resizable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/interactions/resizeHandle' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/interactions/resizeSensor' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/interactions/selectable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/layers/guides' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/layers/regions' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/locator' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/regions' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/table.bundle' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/table' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/dist/tableBody' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blueprintjs/table/dist/cell/cell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/cell/cell'>;
}
declare module '@blueprintjs/table/dist/cell/editableCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/cell/editableCell'>;
}
declare module '@blueprintjs/table/dist/cell/formats/jsonFormat.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/cell/formats/jsonFormat'>;
}
declare module '@blueprintjs/table/dist/cell/formats/truncatedFormat.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/cell/formats/truncatedFormat'>;
}
declare module '@blueprintjs/table/dist/column.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/column'>;
}
declare module '@blueprintjs/table/dist/common/batcher.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/common/batcher'>;
}
declare module '@blueprintjs/table/dist/common/cell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/common/cell'>;
}
declare module '@blueprintjs/table/dist/common/classes.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/common/classes'>;
}
declare module '@blueprintjs/table/dist/common/clipboard.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/common/clipboard'>;
}
declare module '@blueprintjs/table/dist/common/contextMenuTargetWrapper.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/common/contextMenuTargetWrapper'>;
}
declare module '@blueprintjs/table/dist/common/errors.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/common/errors'>;
}
declare module '@blueprintjs/table/dist/common/grid.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/common/grid'>;
}
declare module '@blueprintjs/table/dist/common/index.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/common/index'>;
}
declare module '@blueprintjs/table/dist/common/loadableContent.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/common/loadableContent'>;
}
declare module '@blueprintjs/table/dist/common/rect.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/common/rect'>;
}
declare module '@blueprintjs/table/dist/common/requestIdleCallback.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/common/requestIdleCallback'>;
}
declare module '@blueprintjs/table/dist/common/roundSize.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/common/roundSize'>;
}
declare module '@blueprintjs/table/dist/common/utils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/common/utils'>;
}
declare module '@blueprintjs/table/dist/headers/columnHeader.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/headers/columnHeader'>;
}
declare module '@blueprintjs/table/dist/headers/columnHeaderCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/headers/columnHeaderCell'>;
}
declare module '@blueprintjs/table/dist/headers/editableName.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/headers/editableName'>;
}
declare module '@blueprintjs/table/dist/headers/header.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/headers/header'>;
}
declare module '@blueprintjs/table/dist/headers/headerCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/headers/headerCell'>;
}
declare module '@blueprintjs/table/dist/headers/rowHeader.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/headers/rowHeader'>;
}
declare module '@blueprintjs/table/dist/headers/rowHeaderCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/headers/rowHeaderCell'>;
}
declare module '@blueprintjs/table/dist/index.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/index'>;
}
declare module '@blueprintjs/table/dist/interactions/dragEvents.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/interactions/dragEvents'>;
}
declare module '@blueprintjs/table/dist/interactions/draggable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/interactions/draggable'>;
}
declare module '@blueprintjs/table/dist/interactions/menus/copyCellsMenuItem.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/interactions/menus/copyCellsMenuItem'>;
}
declare module '@blueprintjs/table/dist/interactions/menus/index.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/interactions/menus/index'>;
}
declare module '@blueprintjs/table/dist/interactions/menus/menuContext.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/interactions/menus/menuContext'>;
}
declare module '@blueprintjs/table/dist/interactions/reorderable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/interactions/reorderable'>;
}
declare module '@blueprintjs/table/dist/interactions/resizable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/interactions/resizable'>;
}
declare module '@blueprintjs/table/dist/interactions/resizeHandle.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/interactions/resizeHandle'>;
}
declare module '@blueprintjs/table/dist/interactions/resizeSensor.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/interactions/resizeSensor'>;
}
declare module '@blueprintjs/table/dist/interactions/selectable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/interactions/selectable'>;
}
declare module '@blueprintjs/table/dist/layers/guides.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/layers/guides'>;
}
declare module '@blueprintjs/table/dist/layers/regions.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/layers/regions'>;
}
declare module '@blueprintjs/table/dist/locator.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/locator'>;
}
declare module '@blueprintjs/table/dist/regions.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/regions'>;
}
declare module '@blueprintjs/table/dist/table.bundle.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/table.bundle'>;
}
declare module '@blueprintjs/table/dist/table.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/table'>;
}
declare module '@blueprintjs/table/dist/tableBody.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/tableBody'>;
}
