# @Author: guiguan
# @Date:   2017-02-15T07:18:20+11:00
# @Last modified by:   guiguan
# @Last modified time: 2017-05-16T23:50:54+10:00

outlinks:
  - dbenvy
volumes:
  - srcNode: yarn-cache
workflows:
  - mlaunchInitSingle
  - install
  - test
  - cleanup
